export const PRODUCTS = [
  {
    id: 'macbook-pro',
    name: 'MacBook Pro 16"',
    description: '32GB RAM, 1TB SSD, advanced Retina display, and long battery life.',
    category: 'electronics',
    subCategory: 'laptops',
    price: 2499.99,
    listPrice: 2799.99,
    rating: 4.9,
    reviewsCount: 1840,
    imageUrl: '/assets/macbook.jpg',
    isBestSeller: true,
    savePercent: 11,
    brand: 'Apple',
    colors: ['Silver', 'Space Gray'],
    tags: ['Retina', 'Workstation'],
  },
  {
    id: 'smartphone-pro',
    name: 'Smartphone Pro',
    description: 'Titanium frame, advanced AI camera, fast charging, and 120Hz display.',
    category: 'electronics',
    subCategory: 'smartphones',
    price: 1199.99,
    listPrice: 1299.99,
    rating: 4.7,
    reviewsCount: 920,
    imageUrl: '/assets/smartphone.jpg',
    savePercent: 8,
    brand: 'Vertex',
    colors: ['Titanium Black', 'Natural Titanium'],
    tags: ['Snapdragon', '5G'],
  },
  {
    id: 'headphones-anc',
    name: 'Noise Cancelling Headphones',
    description: 'Active noise cancellation, long battery life, and ergonomic comfort.',
    category: 'electronics',
    subCategory: 'audio',
    price: 299.99,
    listPrice: 349.99,
    rating: 4.5,
    reviewsCount: 430,
    imageUrl: '/assets/headphones.jpg',
    isBestSeller: true,
    brand: 'AuraAudio',
    colors: ['Arctic White', 'Cognac Brown'],
    tags: ['Wireless', 'ANC'],
  },
  {
    id: 'linen-dress',
    name: 'Linen Summer Dress',
    description: 'Breathable linen dress with adjustable waist sash and breezy summer styling.',
    category: 'fashion',
    subCategory: 'dresses',
    price: 84.99,
    listPrice: 109.99,
    rating: 4.6,
    reviewsCount: 210,
    imageUrl: '/assets/dress.jpg',
    brand: 'SunWoven',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sage Green', 'Navy Blue'],
    isSustainable: true,
    tags: ['Summer Essentials', 'Sustainable'],
  },
  {
    id: 'button-up',
    name: 'Classic Button-Up Shirt',
    description: 'Tailored cotton shirt with a modern fit and crisp finish.',
    category: 'fashion',
    subCategory: 'tops',
    price: 54.99,
    listPrice: 69.99,
    rating: 4.4,
    reviewsCount: 165,
    imageUrl: '/assets/shirt.jpg',
    brand: 'Everyday Label',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Classic White', 'Midnight Blue'],
    tags: ['Smart Casual'],
  },
  {
    id: 'cork-sandals',
    name: 'Cork Footbed Sandals',
    description: 'Comfortable sandals with a natural cork footbed and flexible EVA outsole.',
    category: 'fashion',
    subCategory: 'footwear',
    price: 74.99,
    listPrice: 89.99,
    rating: 4.3,
    reviewsCount: 95,
    imageUrl: '/assets/sandals.jpg',
    brand: 'TerraSol',
    sizes: ['7', '8', '9', '10'],
    colors: ['Cognac'],
    tags: ['Leather', 'Cork Footbed'],
  },
  {
    id: 'vitamin-c-serum',
    name: 'Vitamin C Brightening Serum',
    description: 'Hydrating serum to brighten skin, reduce fine lines, and restore radiance.',
    category: 'beauty',
    subCategory: 'skincare',
    price: 39.99,
    listPrice: 49.99,
    rating: 4.8,
    reviewsCount: 340,
    imageUrl: '/assets/serum.jpg',
    isBestSeller: true,
    brand: 'PureGlow',
    tags: ['Brightening', 'Vegan'],
  },
  {
    id: 'rosewood-perfume',
    name: 'Rosewood Perfume',
    description: 'Warm rosewood perfume with sandalwood and creamy vanilla notes.',
    category: 'beauty',
    subCategory: 'fragrance',
    price: 69.99,
    listPrice: 79.99,
    rating: 4.6,
    reviewsCount: 150,
    imageUrl: '/assets/perfume.jpg',
    brand: 'Maison Vitae',
    isLimitedEdition: true,
    tags: ['Eau de Parfum', 'Artisan'],
  },
];

export const CATEGORIES = [
  {
    id: 'electronics',
    name: 'Electronics',
    tagline: 'Cutting-edge gadgets and devices.',
    image: '/assets/category-electronics.jpg',
  },
  {
    id: 'fashion',
    name: 'Fashion',
    tagline: 'Seasonal styles and effortless comfort.',
    image: '/assets/category-fashion.jpg',
  },
  {
    id: 'beauty',
    name: 'Beauty',
    tagline: 'Premium skincare and wellness essentials.',
    image: '/assets/category-beauty.jpg',
  },
];
